### ISSUE TITLE
Add option to return all results for a query

### ISSUE THREAD

**Issue by typpo** [CivilServiceUSA/api#39]
#### Overview:

Querying House legislators by zip code returns 1 representative, but some zip codes (eg. 94043) cover an area with 2 or more representatives.

#### Acceptance Criteria:

Querying House legislators with a new query parameter (eg. `all=true`) will return all results, rather than just 1 result.

#### Steps to Duplicate _( required for bug reports )_:

1.  Load https://api.civil.services/v1/house/?apikey=XXX&zipcode=94043

Expected: 2 results
Actual: 1 result

**Comment by walker** [comment]
Is a particular legislator being excluded because they cover a zipcode but have no constituents in that zip code? (industrial area, gerrymandering connection, or other)

**Comment by manifestinteractive** [comment]
Hey @walker, I talked to @typpo about this issue earlier on Slack.  There are a quite a few instances where Zip Codes return more than one district since zip codes are not exact locations.  What I was doing on the API side of things was using ElasticSearch ( ES ) to return the "most likely" which made it pretty hard for more than one district to get returned ( though still technically possible ).

I will work on updating the ES shape indexing to allow a custom param to be passed in to allow the query to be more forgiving for those knowingly asking for it to be.

Larger cities with dense population are naturally going to have overlapping districts when using the zip code as a means of lookup.  Without an exact GeoLocation, we are literally just comparing the shape of the zip code to the shape of the districts and looking for overlaps.  There are ways to check which overlap is bigger, so that is what was going on under the hood ( if I recall ).  So all I really need to do check for the custom param that says I want ALL districts ( when using a ZipCode ) and return all the districts the zip code has contained in it.

Google Civic does the opposite, where if a location has more than one district being returned, it returns none at all.  The logic, which is what I had to consider as well, is that the data is likely going to be used to tell the person on the other end of the data who their person is they should contact.  It's not very useful to say "One of these people is your elected official, but we don't know which one" ... so not showing any results is actually safer.

**Comment by walker** [comment]
@manifestinteractive Sounds about right. You will find, tho, that there are a TON of times where population of a district w/in a zip code (where it's not "most likely) is zero (or pretty close to zero).

I think the resolution here might be:

a) return most-likely by default
b) return all if requested

**Comment by manifestinteractive** [comment]
@walker ya, that was the plan, which is why @typpo requested the new param, so we keep the current default, but allow for a custom param for those that want to return all if requested.

**Comment by typpo** [comment]
Wondering if either of you had a chance to look at this.

If you point me to the relevant code, I would be happy to take a stab at the change!  I've had a few users of the call congress hotline complain that their representative is not being included in the list so I am hoping to resolve this asap.

**Comment by manifestinteractive** [comment]
Hey @typpo just an update that @skylerkatz is going to take a look at this.  A few days after your reported issues, I ended up scrambling to replace a full time job that just kind of ran out of money to pay its employees.  I just started a new job here this week, so things have been crazy on my end for about 2-3 months now.

Sorry for the delays :(

**Comment by typpo** [comment]
Hi Peter, sorry to hear about the trouble but I am relieved to hear that you got a new job.  Congratulations!  And thank you for looping @skylerkatz in on this issue.

I've just been informed that the Call Congress number is going to be used for a big Net Neutrality push soon.  This is good news for us but means I need to scramble tonight to introduce a fix for the issue with representatives, even if it's temporary!  #41 looks pretty close to being done so I will keep an eye on this but probably set up a temp mapping.
